spring:
# REDIS
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    password: redis
    timeout:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）;如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 8
        #连接池最大阻塞等待时间（负数表示没有限制）;等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: -1
        #连接池最大的空闲链接;默认值也是8。
        max-idle: 8
        #连接池最小的空闲链接;默认值也是8。
        min-idle: 0
    lettuce:
      pool:
        #连接池最小空闲连接，默认值也是0。
        max-active:
        #连接池最大的空闲链接;默认值也是8。
        max-idle:
        #连接池最大阻塞等待时间（负数表示没有限制）;等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait:
        #连接池最小的空闲链接;默认值也是8。
        min-idle: 0
